### ISSUE TITLE
Highlight current row in table

### ISSUE THREAD

**Issue by fvorraa** [bouvet/instant#3]
It should be possible to configure the color to use as background color for the current row in the table.

**Comment by OysteinAmundsen** [comment]
By what do you measure "current row"? The one returned by the `(rowClicked)` event?

**Comment by OysteinAmundsen** [comment]
You can now provide the instant-grid with an row index it should highlight. You have to provide the styling for the highlight yourself.

Additionally I've added a data property to each row, so you can programmatically do anything you like to each row index.
